CommentSection
Elaech/A7-IP pull request #63
Opened 2020-05-09 14:09 UTC by tiberiu1999

Create-commentSection

2020-05-11 07:15 UTC, vdexamir requested changes

2020-05-11 07:15 UTC, Vlad-dexamir commented on Final Project/Client/fiimentor/main/components/CommentSupportComponent/CommentSupport.jsx
> +                        (formikProps: FormikProps<CommentFormValues>) => {
pe astea nu ar trebui sa le faci cu formik, ca tu nu trimiti datele nicaieri...nici nu ai nevoie de formular

2020-05-13 11:41 UTC, vdexamir approved these changes

2020-05-14 19:40 UTC, Dominte approved these changes

2020-05-14 19:40 UTC, merged