Added LastPosts-form
Elaech/A7-IP pull request #66
Opened 2020-05-10 13:02 UTC by tiberiu1999

Added LastPosts-form

2020-05-11 07:16 UTC, vdexamir requested changes

2020-05-11 07:16 UTC, Vlad-dexamir commented on Final Project/Client/fiimentor/pages/index.jsx
> +    <Dashboard/>
lasa cum era...cu loginul

2020-05-11 07:16 UTC, Vlad-dexamir commented on Final Project/Client/fiimentor/main/components/DashboardComponent/DashboardStyles.jsx
> +export const ButtonStyles = styled.div `
de ce nu le folosesti pe cele existente deja?

2020-05-11 07:16 UTC, Vlad-dexamir commented on Final Project/Client/fiimentor/main/components/DashboardComponent/Dashboard.jsx
> +
ar trebui creat un array de postari, ca un mockData...de test ca si cum....si cu el faci map si pui postarea

2020-05-13 11:40 UTC, vdexamir approved these changes

2020-05-14 19:41 UTC, Dominte approved these changes

2020-05-14 19:41 UTC, merged